FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r /app/requirements.txt

COPY Tienda_Online/ /app/Tienda_Online/

RUN chmod -R 755 /app

CMD ["python", "Tienda_Online/main.py"]
